package pw.ohm.yb.lexer;

import java.util.EnumSet;
import java.util.Set;

public enum YbTokens {
	LPAR,
	RPAR, COMMENT, COLON, COMMA, RBRACKET, LBRACKET, RBRACE, LBRACE, EQ, AT, SHARP, DOT, STRING, WHITE_SPACE, BAD_CHARACTER, IDENTIFIER, ITEM_BUILDER_KEYWORD, QUERY_BUILDER_KEYWORD, INT_KEYWORD, LONG_KEYWORD, BOOL_INT_KEYWORD, MAP_KEYWORD, STRING_KEYWORD, DOUBLE_KEYWORD, VARIABLE, BUILDER, VARIABLE_NAME, CONSTANT, REFERENCE, ENUM_TYPE, USER_TYPE, PRIMITIVE_TYPE, PARAMETER, ATTRIBUTE_PARAMETER_LIST, ATTRIBUTE;

	static Set<YbTokens> SOFT_KEYWORDS = EnumSet.of(ITEM_BUILDER_KEYWORD, QUERY_BUILDER_KEYWORD, INT_KEYWORD, BOOL_INT_KEYWORD, MAP_KEYWORD, STRING_KEYWORD, LONG_KEYWORD, DOUBLE_KEYWORD);

	static Set<YbTokens> BUILDER_TOKENS = EnumSet.of(YbTokens.ITEM_BUILDER_KEYWORD, YbTokens.QUERY_BUILDER_KEYWORD);
}
